### ISSUE TITLE
Downloading Image Files

### ISSUE THREAD

**Issue by ansario** [sonic182/aiosonic#123]
**Describe the bug**
When downloading jpeg files using `aiosonic` we receive the following:

```
'utf-8' codec can't decode byte 0x85 in position 2: invalid start byte
Traceback (most recent call last):
  File "./clients/http_client.py", line 28, in query_url
    response = await aiosonic.get("https://example.com/1.jpg")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiosonic/__init__.py", line 463, in get
    return await request(url, 'GET', headers, params, connector=connector,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiosonic/__init__.py", line 566, in request
    response = await asyncio.wait_for(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiosonic/__init__.py", line 402, in _do_request
    response._set_response_initial(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiosonic/__init__.py", line 130, in _set_response_initial
    _HTTP_RESPONSE_STATUS_LINE, data.decode().rstrip('\r\n'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 2: invalid start byte
```

**To Reproduce**
1. Use `aiosonic` to `GET` a JPEG image link.

**Expected behavior**
Proper download of image.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Browser N/A

**Comment by sonic182** [comment]
Thanks for the issue report!

I think I haven't worked with that case (download an Image), despite that, the error seems to be reading/parsing the headers, you could check maybe with curl the response you're having

I'll add some tests for image download

**Comment by sonic182** [comment]
hi @ansario 

I added an example of downloading image in https://aiosonic.readthedocs.io/en/latest/examples.html for version [0.7.0](https://github.com/sonic182/aiosonic/releases/tag/0.7.0)

Please check with this version if the issue still happens

**Comment by ansario** [comment]
Perfect, thanks!
