### ISSUE TITLE
Type Error: 

### ISSUE THREAD

**Issue by machinexa2** [sonic182/aiosonic#181]
```py
import aiosonic
import asyncio
from aiosonic import Timeouts
async def run():
    client = aiosonic.HTTPClient()
    timeouts = Timeouts(sock_read=12, sock_connect=8)
    r = await client.get('https://en.wikipedia.org/wiki/Dextrorphan', timeouts=timeouts)
    print(r.response_initial)
    print(r.headers)

loop  = asyncio.get_event_loop()
loop.run_until_complete(run())
```
This code produces error. There is also same issue related to header https://github.com/sonic182/aiosonic/issues/176 for which i opened a pull request https://github.com/sonic182/aiosonic/pull/180 which i have opened pull request. Just merge that pull request and i will will add more pull request if i can

**Comment by machinexa2** [comment]
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 8, in run
    r = await client.get('https://en.wikipedia.org/wiki/Dextrorphan', timeouts=timeouts)
  File "/usr/local/lib/python3.8/dist-packages/aiosonic/__init__.py", line 483, in get
    return await self.request(url,
  File "/usr/local/lib/python3.8/dist-packages/aiosonic/__init__.py", line 658, in request
    response = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/dist-packages/aiosonic/__init__.py", line 407, in _do_request
    response._set_header(*HttpHeaders._clear_line(res_data))
TypeError: _set_header() takes 3 positional arguments but 7 were given
```

**Comment by machinexa2** [comment]
Merge this first: https://github.com/sonic182/aiosonic/pull/180

**Comment by machinexa2** [comment]
This response header causes errors:
```
b'Report-To: { "group": "wm_nel", "max_age": 86400, "endpoints": [{ "url": "https://intake-logging.wikimedia.org/v1/events?stream=w3c.reportingapi.network_error&schema_uri=/w3c/reportingapi/network_error/1.0.0" }] }\r\n'
b'NEL: { "report_to": "wm_nel", "max_age": 86400, "failure_fraction": 0.05, "success_fraction": 0.0}\r\n'
```
cause _set_header cant parse it

**Comment by machinexa2** [comment]
First merge this: https://github.com/sonic182/aiosonic/issues/176

**Comment by machinexa2** [comment]
I found the solutiion just merge #180 and then just mention me i will open another pull request which fix thsi problem

**Comment by sonic182** [comment]
@machinexa2 Hi, I was on vacations, gonna check the issues you opened this afternoon. Maybe I open a gitter or discord for quick chat
