### ISSUE TITLE
HttpParse error

### ISSUE THREAD

**Issue by machinexa2** [sonic182/aiosonic#182]
```py
from perfplot import show
from requests import get
import aiosonic
from aiosonic import Timeouts
from requests import Session
import asyncio

append1, append2 = [], []
timeouts = Timeouts(sock_read=12, sock_connect=12)

def gen_urls(r):
    mega_url = []
    for i in range(r):
        mega_url.append('http://google.com/')
        mega_url.append('http://yahoo.com/')
        mega_url.append('https://github.com/sonic182/aiosonic/pulls')
        mega_url.append('https://stackoverflow.com/questions/6903557/splitting-on-first-occurrence')
        mega_url.append('https://en.wikipedia.org/wiki/Dextromethorphan')
        mega_url.append('https://discord.com/channels/@me/716265091489595473got')
    return mega_url

def async_run(urls):
    async def main():
        global append1
        client = aiosonic.HTTPClient()
        for url in urls:
            print(url)
            response = await client.get(url, timeouts=timeouts)
            append1.append(response.headers)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

def request_run(urls):
    global append2
    s = Session()
    for url in urls:
        print(url)
        response = s.get(url)
        append2.append(response.headers)

show(
    setup=lambda n: gen_urls(n),
    kernels=[
        async_run,
        request_run,
    ],
    n_range=[k for k in range(6)],
    equality_check=None
)

```
When profiling the code for performance, I got this error. I am confused how i got this error
```
Traceback (most recent call last):
  File "Fastreq.py", line 41, in <module>
    show(
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 328, in show
    out = bench(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 231, in bench
    t, total_time = _b(
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 266, in _b
    timeit.repeat(
  File "/usr/lib/python3.8/timeit.py", line 238, in repeat
    return Timer(stmt, setup, timer, globals).repeat(repeat, number)
  File "/usr/lib/python3.8/timeit.py", line 205, in repeat
    t = self.timeit(number)
  File "/usr/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 267, in <lambda>
    stmt=lambda: kernel(data), repeat=repeat, number=number, timer=timer
  File "Fastreq.py", line 31, in async_run
    loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Fastreq.py", line 28, in main
    response = await client.get(url, timeouts=timeouts)
  File "/usr/local/lib/python3.8/dist-packages/aiosonic-0.7.0-py3.8.egg/aiosonic/__init__.py", line 484, in get
  File "/usr/local/lib/python3.8/dist-packages/aiosonic-0.7.0-py3.8.egg/aiosonic/__init__.py", line 659, in request
  File "/usr/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/dist-packages/aiosonic-0.7.0-py3.8.egg/aiosonic/__init__.py", line 396, in _do_request
  File "/usr/local/lib/python3.8/dist-packages/aiosonic-0.7.0-py3.8.egg/aiosonic/__init__.py", line 130, in _set_response_initial
aiosonic.exceptions.HttpParsingError: response line parsing error
```

**Comment by machinexa2** [comment]
I got this error multiple times, BTW, i have added a pull request merge that first, i am using that pull request version as 0.7.0 errors out in wikipedia

**Comment by sonic182** [comment]
https://github.com/sonic182/aiosonic/issues/181 seems to be fixed with the latest release (was fixed in PR https://github.com/sonic182/aiosonic/pull/186) https://github.com/sonic182/aiosonic/releases/tag/0.7.1

@machinexa2  can you check this example too? or tell me the dependencies so I could try to fix here too

**Comment by sonic182** [comment]
Seems to be working (on my macbook 13 2017) @machinexa2 

![image](https://user-images.githubusercontent.com/4070466/99889668-d8711a80-2c57-11eb-8d5b-be3c9d6900da.png)

I'll close the issue for now
