### ISSUE TITLE
aiosonic.exceptions.HttpParsingError: missing hostname

### ISSUE THREAD

**Issue by Wykt** [sonic182/aiosonic#317]
Have this error

`Traceback (most recent call last):
  File "asyncchecker.py", line 46, in check
    req = await client.post(url, headers={
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosonic\__init__.py", line 663, in post
    return await self._request_with_body(
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosonic\__init__.py", line 609, in _request_with_body
    return await self.request(
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosonic\__init__.py", line 839, in request
    response = await wait_for(
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosonic\__init__.py", line 491, in _do_request
    async with (await connector.acquire(*args)) as connection:
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\aiosonic\connectors.py", line 71, in acquire
    raise HttpParsingError("missing hostname")
aiosonic.exceptions.HttpParsingError: missing hostname`

Any idea why is this happening, please ?

Edit: Proxy is the problem, I don't know why tho

**Comment by sonic182** [comment]
Are you sending a file? Tell me what are you doing so I can replicate it please :)

**Comment by Wykt** [comment]
I'm sending a post request with proxies, just headers and a json body

**Comment by Wykt** [comment]
So?

**Comment by sonic182** [comment]
I was in vacation, gonna try this week to check it

**Comment by sonic182** [comment]
I cannot reproduce your error

```python
import asyncio
import json

from aiosonic import HTTPClient, Proxy


async def main():
    """
    To run proxy server:

    > pip install --upgrade proxy.py
    > proxy
    """
    async with HTTPClient(proxy=Proxy("http://localhost:8899")) as client:
        responses = await asyncio.gather(
            *[
                client.post(
                    "https://postman-echo.com/post", json={"foo": "bar", "try": i}
                )
                for i in range(10)
            ]
        )

        for res in responses:
            print(res)
            print(json.dumps(await res.json(), indent=10))
            assert res.status_code == 200

        for i in range(15):
            res = await client.post(
                "https://postman-echo.com/post", json={"foo": "bar", "try": i}
            )
            print(res)
            print(json.dumps(await res.json(), indent=10))
            assert res.status_code == 200


asyncio.run(main())
```
